name: End-to-end test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  end-to-end-test:
    strategy:
      fail-fast: true
      # matrix:
      #   os: [ubuntu-22.04, macos-12]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Install required tools and Python packages
        run: |
          sudo apt update
          sudo apt install wget unzip flake8
          pip3 install psutil
          docker pull adfreiburg/qlever
          # docker run adfreiburg/qlever --help | head

      - name: Format and compile check
        run: |
          flake8 qlever.py
          python3 -m py_compile qlever.py

      - name: Test actions for olympics dataset
        working-directory: ${{github.workspace}}
        run: |
          mkdir olympics
          cp -a Qleverfile.ini olympics
          cd olympics
          script -q -c "../qlever.py get-data docker.USE_DOCKER=true index start status stop status"
          ls -lh
