name: End-to-end test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  end-to-end-test:
    strategy:
      fail-fast: true
      # matrix:
      #   os: [ubuntu-22.04, macos-12]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Install required tools and Python packages
        run: |
          sudo apt update
          sudo apt install wget unzip flake8
          pip3 install psutil
          # docker run adfreiburg/qlever --help | head

      - name: Install latest version of QLever (download Docker image and compile natively)
        working-directory: ${{github.workspace}}
        run: |
          docker pull adfreiburg/qlever
          git clone --recursive https://github.com/ad-freiburg/qlever qlever-code
          cd qlever-code
          cat Dockerfile | sed -En 's/(add-apt|apt|tee)/sudo \1/g; s/^RUN //p' | sed '/^cmake/q' | sed -E 's/^(cmake.*)/mkdir -p build \&\& cd build\n\1\ncd ../' | sed -n '/^sudo/p' > INSTALL
          cat INSTALL
          source ./INSTALL
          mkdir qlever-binaries
          wget https://ad-research.cs.uni-freiburg.de/downloads/qlever/ServerMain
          wget https://ad-research.cs.uni-freiburg.de/downloads/qlever/IndexBuilderMain
          chmod 755 ServerMain IndexBuilderMain
          export PATH="$PATH:$(pwd)/qlever-binaries"

      - name: Format and compile check
        run: |
          flake8 qlever.py
          python3 -m py_compile qlever.py

      - name: Test actions for olympics dataset, with Docker
        working-directory: ${{github.workspace}}
        run: |
          mkdir olympics.with-docker && cd $_
          cp -a ../Qleverfile.ini .
          script -q -c "../qlever.py get-data docker.USE_DOCKER=true index start status stop status"
          ls -lh

      - name: Test actions for olympics dataset, without Docker
        working-directory: ${{github.workspace}}
        run: |
          echo $PATH
          ServerMain --help | head -1
          IndexBuilderMain --help | head -1
          mkdir olympics.without-docker && cd $_
          cp -a ../Qleverfile.ini .
          script -q -c "../qlever.py get-data docker.USE_DOCKER=false index start status stop status"
          ls -lh
